experiment_name: 'exp_monai_unet'

paths:
  results_dir: "results"
  model_dir: "scripts/models/"
  data_visualizations_dir: "data/"

model:
  filename: 'monai_unet.py'
  class_name: 'UNet'
  spatial_dims: 2                      # 2D images
  in_channels: 3                       # RGB input (3 channels)
  out_channels: 1                      # Binary segmentation (1 output channel)
  channels: [64, 128, 256, 512]        # Channel progression
  strides: [2, 2, 2]                   # Downsampling steps
  num_res_units: 0                     # Residual blocks per stage
  norm: 'batch'                        #  normalization
  act: "relu"                          # ReLU activation
  dropout: 0.2                         #  dropout
  bias: True                           # Include bias terms

loss:
  sigmoid: True
  include_background: False
  lambda_dice: 0.7
  lambda_ce: 0.3
#  weight: [0.1, 0.9]

batch_size: 16
num_workers: 4
pin_memory: True
persistent_workers: True
epochs: 100
optimizer:
  name: 'Adam'
  learning_rate: 0.001
  scheduler: CosineAnnealingLR


metrics: [
  'mIoU',
  'mDice',
  'f2_score',
  'precision',
  'recall',
  'accuracy',
]

