experiment_name: 'exp_monai_unet'

paths:
  results_dir: "results"
  model_dir: "scripts/models/"
  data_visualizations_dir: "data/"

model:
  filename: 'monai_unet.py'
  class_name: 'UNet'
  spatial_dims: 2                      # 2D images
  in_channels: 3                       # RGB input (3 channels)
  out_channels: 1                      # Binary segmentation (1 output channel)
  channels: [16, 32, 64, 128, 256]     # Channel progression
  strides: [2, 2, 2, 2]                # Downsampling steps
  num_res_units: 0
  norm: 'batch'                        #  normalization
  act: "relu"                          # ReLU activation
  dropout: 0.1                         # dropout
  bias: True                           # bias in conv layers

loss:
  sigmoid: True
  include_background: False
  lambda_dice: 0.5
  lambda_ce: 0.5
  # weight: 1.1

batch_size: 32
val_split: 0.2
epochs: 300
optimizer: 'Adam'
learning_rate: 0.0003
weight_decay: 0 #0.00001 # 0.0001
scheduler: ReduceLROnPlateau #None #CosineAnnealingLR


metrics: [
  'mIoU',
  'mDice',
  'f2_score',
  'precision',
  'recall',
  'accuracy',
]

