name: effisegnet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - absl-py
  - aiohttp
  - aiosignal
  - anyio
  - arrow
  - attrs
  - backoff
  - beautifulsoup4
  - blas
  - blessed
  - blinker
  - boto3
  - botocore
  - brotli-python
  - bzip2
  - ca-certificates
  - cachecontrol
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - cryptography
  - cuda-cudart=11.8
  - cuda-cupti=11.8
  - cuda-libraries=11.8
  - cuda-nvrtc=11.8
  - cuda-nvtx=11.8
  - cuda-runtime=11.8
  - fastapi
  - ffmpeg
  - filelock
  - freetype
  - frozenlist
  - fsspec
  - giflib
  - gmp
  - gnutls
  - google-auth
  - google-auth-oauthlib
  - grpcio
  - h11
  - idna
  - importlib-metadata
  - jinja2
  - jmespath
  - jpeg
  - keyring
  - lcms2
  - libdeflate
  - libffi
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtiff
  - libunistring
  - libuuid
  - libwebp
  - lightning
  - lightning-cloud
  - lightning-utilities
  - lz4-c
  - markdown
  - markupsafe
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - monai
  - more-itertools
  - msgpack-python
  - multidict
  - ncurses
  - nettle
  - networkx
  - numpy
  - oauthlib
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pillow
  - pip:
      - torch
      - torchvision
      - torchaudio
  - protobuf
  - pydantic
  - pygments
  - python-dateutil
  - python-dotenv
  - pytorch-cuda=11.8
  - pyyaml
  - readline
  - requests
  - rich
  - scipy
  - setuptools
  - six
  - soupsieve
  - sqlite
  - starlette
  - sympy
  - tensorboard
  - tk
  - tomlkit
  - tornado
  - tqdm
  - typing-extensions
  - tzdata
  - urllib3
  - uvicorn
  - virtualenv
  - wcwidth
  - wheel
  - xz
  - yarl
  - zipp
  - zlib
  - zstd
